### ISSUE TITLE
Renaming this repo and team

### ISSUE THREAD

**Issue by orangemocha** [nodejs/Future-CI#7]
I have seen people mention @nodejs/ci when something goes wrong with the current Jenkins system, assuming that it's the alias for a support team for the current CI. For that purpose, the "right" team has historically been @nodejs/build though the scope of build can be broader than just CI. We have @nodejs/jenkins-admins which more accurately reflect the people who actually manage the CI, though that reflects permissions rather than a support team. For example, I think that some people from @nodejs/testing would be interested in notification about CI issues.

Idea: can we rename this repo and corresponding team to NextGen-CI or CI-NG, and use the ci alias (and potentially the repo) for supporting the _current_ CI?

Or is @nodejs/build the right alias to ping for CI issues?

**Comment by yorkie** [comment]
+1 on CI-NG

**Comment by jbergstroem** [comment]
Makes sense. Lets rename this.

**Comment by Fishrock123** [comment]
Since this is mostly my thing, I've gone ahead and renamed it to future-ci.

I'd still like to take this up, but that is now a fairly distant future.

**Comment by orangemocha** [comment]
Thanks @Fishrock123. At the last Build WG meeting we decided to keep (and document) nodejs/build as the alias for CI support. But renaming this repo and team to 'future-ci' still helps avoid confusion.
